### PR TITLE
Add Support for gerrit review for pac repos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Nick0703** [comment]
Please submit it to gerrit. We no longer accept PR from github.

**Comment by ghost** [comment]
Can someone push it!
I cant get to push to gerrit
it say "everything up to date"

**Comment by gs2usr** [comment]
If your doing a cherry pick it will say that, just push it and it will show once it's in gerrit

**Comment by singhdd93** [comment]
Sent a review on gerrit

**Pull request closed without merging**
